name: Daily Commit Automation

on:
  schedule:
    - cron: '30 5 * * *'  # Runs daily at 5:30 AM UTC
  workflow_dispatch:       # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update timestamp
        run: echo "$(date)" > last_update.txt

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Step containing your email ID as required
      - name: Commit changes [23f2005219@ds.study.iitm.ac.in]
        run: |
          git add last_update.txt
          git commit -m "Automated daily update"
          git push origin main
