name: Daily Commit Automation

on:
  schedule:
    - cron: '30 5 * * *'  # Daily at 5:30 AM UTC (11:00 AM IST)
  workflow_dispatch:       # Enable manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Required for push access
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Authentication token

      - name: Update timestamp
        run: echo "$(date)" > last_update.txt

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Step containing your email ID in its name
      - name: Commit changes [23f2005219@ds.study.iitm.ac.in]
        run: |
          git add last_update.txt
          git commit -m "Automated daily update"
          git push origin main
